name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and release apk
        uses: stevan-a/buildozer-action@v1.4.1
        with:
          # Use a specific Python version
          python-version: "3.9"
          # Command to run buildozer
          command: "buildozer android debug"

      - name: Upload a Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: utkachat-apk
          path: bin/*.apk
